server:
  port: 8019
spring:
  application:
    name: order-client
ribbon:
  eureka:
    enable: true
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    #下面一定要写 true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8888/eureka
feign:
  hystrix :
    enable : true
  command :
    default :
      execution :
        isolation :
          thread :
            timeoutInMilliseconds : 6000
      circuitBreaker :
        forceOpen : true
